name: Playwright Tests
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install serve
      run: npm install -g serve
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Build
      run: pnpm build
    - name: Run Playwright tests
      run:
        source .env.dev
        serve -s dist -l 8080 &
        pnpm exec playwright test
      env: 
        PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:8080'
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
